export const DOGS_START = 'DOGS_START';
export const DOGS_ADD = 'DOGS_ADD';
export const DOGS_COUNT_SUCCESS = 'DOGS_COUNT_SUCCESS';
export const DOGS_NOTIFICATIONS_SUCCESS = 'DOGS_NOTIFICATIONS_SUCCESS';
export const DOGS_SUCCESS = 'DOGS_SUCCESS';
export const DOGS_FAIL = 'DOGS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_UPDATE_SUCCESS = 'AUTH_UPDATE_SUCCESS'; 
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CONTACT_START = 'CONTACT_START';
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
export const CONTACT_FAIL =  'CONTACT_FAIL';

export const USER_START = 'USER_START'; 
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_COUNT_SUCCESS = 'USER_COUNT_SUCCESS'; 
export const USER_SUCCESS_CHATS = 'USER_SUCCESS_CHATS';
export const USER_FAIL = 'USER_FAIL'; 

export const ADMIN_START = 'ADMIN_START';
export const ADMIN_USERS_SUCCESS = 'ADMIN_USERS_SUCCESS';
export const ADMIN_CHATS_SUCCESS = 'ADMIN_CHATS_SUCCESS';
export const ADMIN_UPDATE_SUCCESS = 'ADMIN_UPDATE_SUCCESS';
export const ADMIN_SUCCESS = 'ADMIN_SUCCESS';
export const ADMIN_FAIL = 'ADMIN_FAIL';

